services:
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "8080:3000"
    env_file:
      - .env
    restart: always
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "4040:5000"
    env_file:
      - .env
    restart: always
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - db_data_container:/data/db
volumes:
  db_data_container:
