services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/opt/app"
    environment:
      - "CI=true"
    restart: always
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/opt/app"
    restart: always
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - db_data_container:/data/db
volumes:
  db_data_container:
